-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 10 — STREAMS & TASKS
-- ============================================================
-- Final transformation/MERGE logic will be added after ingestion validation.

USE DATABASE DIVVY_DB;

CREATE STREAM IF NOT EXISTS DIVVY_DB.RAW.STREAM_RAW_TRIPS
    ON TABLE DIVVY_DB.RAW.RAW_TRIPS;

CREATE STREAM IF NOT EXISTS DIVVY_DB.RAW.STREAM_RAW_GBFS
    ON TABLE DIVVY_DB.RAW.RAW_GBFS;

CREATE TASK IF NOT EXISTS DIVVY_DB.CORE.TASK_PROCESS_TRIPS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
    SELECT CURRENT_TIMESTAMP() AS TASK_EXECUTION_TIME;

CREATE TASK IF NOT EXISTS DIVVY_DB.CORE.TASK_PROCESS_GBFS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 5 * * * * UTC'
AS
    SELECT CURRENT_TIMESTAMP() AS TASK_EXECUTION_TIME;

SHOW STREAMS IN SCHEMA DIVVY_DB.RAW;
SHOW TASKS IN SCHEMA DIVVY_DB.CORE;

-- Resume only after final transformation logic is validated.
-- ALTER TASK DIVVY_DB.CORE.TASK_PROCESS_TRIPS RESUME;
-- ALTER TASK DIVVY_DB.CORE.TASK_PROCESS_GBFS RESUME;
