-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 04 — STAGING TABLES & TRANSFORMATION PROCEDURE
-- ============================================================
-- STAGING standardizes RAW data and applies reusable validation.
-- The procedure is called by File 08 after historical RAW loading.
-- GBFS extraction is handled incrementally by File 10.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE TABLE IF NOT EXISTS DIVVY_DB.STAGING.STG_TRIPS
(
    RIDE_ID                VARCHAR,
    RIDEABLE_TYPE          VARCHAR,
    STARTED_AT             TIMESTAMP_NTZ,
    ENDED_AT               TIMESTAMP_NTZ,
    START_STATION_NAME     VARCHAR,
    START_STATION_ID       VARCHAR,
    END_STATION_NAME       VARCHAR,
    END_STATION_ID         VARCHAR,
    START_LAT              NUMBER(10,7),
    START_LNG              NUMBER(10,7),
    END_LAT                NUMBER(10,7),
    END_LNG                NUMBER(10,7),
    MEMBER_CASUAL          VARCHAR,
    TRIP_DURATION_MINUTES  NUMBER(12,2),
    IS_VALID_TIMESTAMP     BOOLEAN,
    IS_VALID_DURATION      BOOLEAN,
    IS_VALID_STATION       BOOLEAN,
    IS_DUPLICATE           BOOLEAN,
    SOURCE_FILE            VARCHAR,
    LOAD_ID                VARCHAR,
    STAGING_TIMESTAMP      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.STAGING.STG_STATION_STATUS
(
    STATION_ID             VARCHAR,
    SNAPSHOT_TIMESTAMP     TIMESTAMP_NTZ,
    STATION_STATUS         VARCHAR,
    NUM_VEHICLES_AVAILABLE NUMBER,
    NUM_DOCKS_AVAILABLE    NUMBER,
    SOURCE_FILE            VARCHAR,
    LOAD_ID                VARCHAR,
    STAGING_TIMESTAMP      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.STAGING.STG_VEHICLE_STATUS
(
    VEHICLE_ID             VARCHAR,
    VEHICLE_TYPE_ID        VARCHAR,
    STATION_ID             VARCHAR,
    LATITUDE               NUMBER(10,7),
    LONGITUDE              NUMBER(10,7),
    VEHICLE_STATUS         VARCHAR,
    SNAPSHOT_TIMESTAMP     TIMESTAMP_NTZ,
    SOURCE_FILE            VARCHAR,
    LOAD_ID                VARCHAR,
    STAGING_TIMESTAMP      TIMESTAMP_NTZ
);

-- ============================================================
-- 04.1 — HISTORICAL RAW → STAGING PROCEDURE
-- ============================================================

CREATE OR REPLACE PROCEDURE DIVVY_DB.STAGING.SP_LOAD_HISTORICAL_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO DIVVY_DB.STAGING.STG_TRIPS AS T
    USING
    (
        SELECT *
        FROM
        (
            SELECT
                RIDE_ID,
                RIDEABLE_TYPE,
                STARTED_AT,
                ENDED_AT,
                START_STATION_NAME,
                START_STATION_ID,
                END_STATION_NAME,
                END_STATION_ID,
                START_LAT,
                START_LNG,
                END_LAT,
                END_LNG,
                MEMBER_CASUAL,
                ROUND(DATEDIFF('millisecond', STARTED_AT, ENDED_AT) / 60000.0, 2) AS TRIP_DURATION_MINUTES,
                STARTED_AT IS NOT NULL AND ENDED_AT IS NOT NULL AS IS_VALID_TIMESTAMP,
                STARTED_AT IS NOT NULL AND ENDED_AT IS NOT NULL AND ENDED_AT >= STARTED_AT AS IS_VALID_DURATION,
                START_STATION_ID IS NOT NULL AND END_STATION_ID IS NOT NULL AS IS_VALID_STATION,
                COUNT(*) OVER (PARTITION BY RIDE_ID) > 1 AS IS_DUPLICATE,
                SOURCE_FILE,
                LOAD_ID,
                CURRENT_TIMESTAMP() AS STAGING_TIMESTAMP,
                ROW_NUMBER() OVER (PARTITION BY RIDE_ID, COALESCE(SOURCE_FILE, '') ORDER BY INGESTION_TIMESTAMP DESC) AS RN
            FROM DIVVY_DB.RAW.RAW_TRIPS
        ) X
        WHERE RN = 1
    ) AS S
    ON T.RIDE_ID = S.RIDE_ID
    AND COALESCE(T.SOURCE_FILE, '') = COALESCE(S.SOURCE_FILE, '')
    WHEN MATCHED THEN UPDATE SET
        RIDEABLE_TYPE = S.RIDEABLE_TYPE,
        STARTED_AT = S.STARTED_AT,
        ENDED_AT = S.ENDED_AT,
        START_STATION_NAME = S.START_STATION_NAME,
        START_STATION_ID = S.START_STATION_ID,
        END_STATION_NAME = S.END_STATION_NAME,
        END_STATION_ID = S.END_STATION_ID,
        START_LAT = S.START_LAT,
        START_LNG = S.START_LNG,
        END_LAT = S.END_LAT,
        END_LNG = S.END_LNG,
        MEMBER_CASUAL = S.MEMBER_CASUAL,
        TRIP_DURATION_MINUTES = S.TRIP_DURATION_MINUTES,
        IS_VALID_TIMESTAMP = S.IS_VALID_TIMESTAMP,
        IS_VALID_DURATION = S.IS_VALID_DURATION,
        IS_VALID_STATION = S.IS_VALID_STATION,
        IS_DUPLICATE = S.IS_DUPLICATE,
        LOAD_ID = S.LOAD_ID,
        STAGING_TIMESTAMP = S.STAGING_TIMESTAMP
    WHEN NOT MATCHED THEN INSERT
    (
        RIDE_ID, RIDEABLE_TYPE, STARTED_AT, ENDED_AT,
        START_STATION_NAME, START_STATION_ID, END_STATION_NAME, END_STATION_ID,
        START_LAT, START_LNG, END_LAT, END_LNG, MEMBER_CASUAL,
        TRIP_DURATION_MINUTES, IS_VALID_TIMESTAMP, IS_VALID_DURATION,
        IS_VALID_STATION, IS_DUPLICATE, SOURCE_FILE, LOAD_ID, STAGING_TIMESTAMP
    )
    VALUES
    (
        S.RIDE_ID, S.RIDEABLE_TYPE, S.STARTED_AT, S.ENDED_AT,
        S.START_STATION_NAME, S.START_STATION_ID, S.END_STATION_NAME, S.END_STATION_ID,
        S.START_LAT, S.START_LNG, S.END_LAT, S.END_LNG, S.MEMBER_CASUAL,
        S.TRIP_DURATION_MINUTES, S.IS_VALID_TIMESTAMP, S.IS_VALID_DURATION,
        S.IS_VALID_STATION, S.IS_DUPLICATE, S.SOURCE_FILE, S.LOAD_ID, S.STAGING_TIMESTAMP
    );

    RETURN 'HISTORICAL_STAGING_COMPLETE';
END;
$$;

SHOW TABLES IN SCHEMA DIVVY_DB.STAGING;
