-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 05 — CORE STAR SCHEMA
-- ============================================================
-- CORE contains trusted dimensions and facts.
-- FACT_TRIP grain: one completed/source trip record.
-- Snapshot facts are one record per source snapshot/entity.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_DATE
(
    DATE_KEY       NUMBER(8,0) PRIMARY KEY,
    FULL_DATE      DATE,
    DAY_OF_WEEK    NUMBER,
    DAY_NAME       VARCHAR,
    DAY_OF_MONTH   NUMBER,
    WEEK_OF_YEAR   NUMBER,
    MONTH_NUMBER   NUMBER,
    MONTH_NAME     VARCHAR,
    QUARTER_NUMBER NUMBER,
    YEAR_NUMBER    NUMBER,
    IS_WEEKEND     BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_TIME
(
    TIME_KEY       NUMBER(6,0) PRIMARY KEY,
    FULL_TIME      TIME,
    HOUR_NUMBER    NUMBER,
    MINUTE_NUMBER  NUMBER,
    SECOND_NUMBER  NUMBER,
    TIME_BUCKET    VARCHAR,
    PEAK_PERIOD    VARCHAR
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_STATION
(
    STATION_KEY      NUMBER AUTOINCREMENT,
    STATION_ID       VARCHAR,
    STATION_NAME     VARCHAR,
    LATITUDE         NUMBER(10,7),
    LONGITUDE        NUMBER(10,7),
    SOURCE_SYSTEM    VARCHAR,
    EFFECTIVE_FROM   TIMESTAMP_NTZ,
    EFFECTIVE_TO     TIMESTAMP_NTZ,
    IS_CURRENT       BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_RIDER
(
    RIDER_KEY        NUMBER AUTOINCREMENT,
    RIDER_TYPE       VARCHAR,
    SOURCE_SYSTEM    VARCHAR,
    IS_CURRENT       BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_VEHICLE
(
    VEHICLE_KEY      NUMBER AUTOINCREMENT,
    VEHICLE_ID       VARCHAR,
    VEHICLE_TYPE_ID  VARCHAR,
    STATION_ID       VARCHAR,
    SOURCE_SYSTEM    VARCHAR,
    IS_CURRENT       BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_VEHICLE_TYPE
(
    VEHICLE_TYPE_KEY  NUMBER AUTOINCREMENT,
    VEHICLE_TYPE_ID   VARCHAR,
    VEHICLE_TYPE_NAME VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    IS_CURRENT        BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.FACT_TRIP
(
    TRIP_KEY             NUMBER AUTOINCREMENT,
    RIDE_ID              VARCHAR,
    START_DATE_KEY       NUMBER(8,0),
    START_TIME_KEY       NUMBER(6,0),
    END_DATE_KEY         NUMBER(8,0),
    END_TIME_KEY         NUMBER(6,0),
    START_STATION_KEY    NUMBER,
    END_STATION_KEY      NUMBER,
    RIDER_KEY            NUMBER,
    RIDEABLE_TYPE        VARCHAR,
    STARTED_AT           TIMESTAMP_NTZ,
    ENDED_AT             TIMESTAMP_NTZ,
    TRIP_DURATION_MINUTES NUMBER(12,2),
    START_LAT             NUMBER(10,7),
    START_LNG             NUMBER(10,7),
    END_LAT               NUMBER(10,7),
    END_LNG               NUMBER(10,7),
    SOURCE_FILE           VARCHAR,
    LOAD_ID               VARCHAR,
    CREATED_AT            TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.FACT_STATION_STATUS
(
    STATION_STATUS_KEY     NUMBER AUTOINCREMENT,
    STATION_KEY            NUMBER,
    DATE_KEY               NUMBER(8,0),
    TIME_KEY               NUMBER(6,0),
    SNAPSHOT_TIMESTAMP     TIMESTAMP_NTZ,
    STATION_STATUS         VARCHAR,
    NUM_VEHICLES_AVAILABLE NUMBER,
    NUM_DOCKS_AVAILABLE    NUMBER,
    SOURCE_FILE            VARCHAR,
    LOAD_ID                VARCHAR,
    CREATED_AT             TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.FACT_VEHICLE_STATUS
(
    VEHICLE_STATUS_KEY NUMBER AUTOINCREMENT,
    VEHICLE_KEY        NUMBER,
    STATION_KEY        NUMBER,
    DATE_KEY           NUMBER(8,0),
    TIME_KEY           NUMBER(6,0),
    SNAPSHOT_TIMESTAMP TIMESTAMP_NTZ,
    VEHICLE_STATUS     VARCHAR,
    LATITUDE           NUMBER(10,7),
    LONGITUDE          NUMBER(10,7),
    SOURCE_FILE        VARCHAR,
    LOAD_ID            VARCHAR,
    CREATED_AT         TIMESTAMP_NTZ
);

SHOW TABLES IN SCHEMA DIVVY_DB.CORE;
