-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 05 — CORE STAR SCHEMA & ELT PROCEDURE
-- ============================================================
-- CORE is the trusted business-oriented layer.
-- FACT_TRIP grain: one valid, non-duplicate source trip.
-- File 08 calls the historical CORE procedure after staging.
-- File 10 performs incremental GBFS CORE processing.
-- ============================================================

USE DATABASE DIVVY_DB;

-- ============================================================
-- 05.0 — CORE SCHEMA COMPATIBILITY
-- ============================================================
-- Existing development databases may contain an earlier version
-- of DIM_TIME and DIM_RIDER. The statements below are deliberately
-- simple and idempotent so the file works in DataGrip/SnowSQL
-- without dynamic SQL or session-variable dependencies.
-- ============================================================

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_DATE
(
    DATE_KEY       NUMBER(8,0) PRIMARY KEY,
    FULL_DATE      DATE,
    DAY_OF_WEEK    NUMBER,
    DAY_NAME       VARCHAR,
    DAY_OF_MONTH   NUMBER,
    WEEK_OF_YEAR   NUMBER,
    MONTH_NUMBER   NUMBER,
    MONTH_NAME     VARCHAR,
    QUARTER_NUMBER NUMBER,
    YEAR_NUMBER    NUMBER,
    IS_WEEKEND     BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_TIME
(
    TIME_KEY       NUMBER(6,0) PRIMARY KEY,
    FULL_TIME      TIME,
    HOUR_NUMBER    NUMBER,
    MINUTE_NUMBER  NUMBER,
    SECOND_NUMBER  NUMBER,
    TIME_BUCKET    VARCHAR,
    PEAK_PERIOD    VARCHAR
);

ALTER TABLE DIVVY_DB.CORE.DIM_TIME
    ADD COLUMN IF NOT EXISTS SECOND_NUMBER NUMBER;

ALTER TABLE DIVVY_DB.CORE.DIM_TIME
    ADD COLUMN IF NOT EXISTS TIME_BUCKET VARCHAR;

ALTER TABLE DIVVY_DB.CORE.DIM_TIME
    ADD COLUMN IF NOT EXISTS PEAK_PERIOD VARCHAR;

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_STATION
(
    STATION_KEY      NUMBER AUTOINCREMENT,
    STATION_ID       VARCHAR,
    STATION_NAME     VARCHAR,
    LATITUDE         NUMBER(10,7),
    LONGITUDE        NUMBER(10,7),
    SOURCE_SYSTEM    VARCHAR,
    EFFECTIVE_FROM   TIMESTAMP_NTZ,
    EFFECTIVE_TO     TIMESTAMP_NTZ,
    IS_CURRENT       BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_RIDER
(
    RIDER_KEY        NUMBER AUTOINCREMENT,
    RIDER_TYPE       VARCHAR,
    SOURCE_SYSTEM    VARCHAR,
    IS_CURRENT       BOOLEAN
);

ALTER TABLE DIVVY_DB.CORE.DIM_RIDER
    ADD COLUMN IF NOT EXISTS RIDER_TYPE VARCHAR;

ALTER TABLE DIVVY_DB.CORE.DIM_RIDER
    ADD COLUMN IF NOT EXISTS SOURCE_SYSTEM VARCHAR;

ALTER TABLE DIVVY_DB.CORE.DIM_RIDER
    ADD COLUMN IF NOT EXISTS IS_CURRENT BOOLEAN;

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_VEHICLE
(
    VEHICLE_KEY      NUMBER AUTOINCREMENT,
    VEHICLE_ID       VARCHAR,
    VEHICLE_TYPE_ID  VARCHAR,
    STATION_ID       VARCHAR,
    SOURCE_SYSTEM    VARCHAR,
    IS_CURRENT       BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.DIM_VEHICLE_TYPE
(
    VEHICLE_TYPE_KEY  NUMBER AUTOINCREMENT,
    VEHICLE_TYPE_ID   VARCHAR,
    VEHICLE_TYPE_NAME VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    IS_CURRENT        BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.FACT_TRIP
(
    TRIP_KEY              NUMBER AUTOINCREMENT,
    RIDE_ID               VARCHAR,
    START_DATE_KEY        NUMBER(8,0),
    START_TIME_KEY        NUMBER(6,0),
    END_DATE_KEY          NUMBER(8,0),
    END_TIME_KEY          NUMBER(6,0),
    START_STATION_KEY     NUMBER,
    END_STATION_KEY       NUMBER,
    RIDER_KEY             NUMBER,
    RIDEABLE_TYPE         VARCHAR,
    STARTED_AT            TIMESTAMP_NTZ,
    ENDED_AT              TIMESTAMP_NTZ,
    TRIP_DURATION_MINUTES NUMBER(12,2),
    START_LAT              NUMBER(10,7),
    START_LNG              NUMBER(10,7),
    END_LAT               NUMBER(10,7),
    END_LNG               NUMBER(10,7),
    SOURCE_FILE           VARCHAR,
    LOAD_ID               VARCHAR,
    CREATED_AT            TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.FACT_STATION_STATUS
(
    STATION_STATUS_KEY     NUMBER AUTOINCREMENT,
    STATION_KEY            NUMBER,
    DATE_KEY               NUMBER(8,0),
    TIME_KEY               NUMBER(6,0),
    SNAPSHOT_TIMESTAMP     TIMESTAMP_NTZ,
    STATION_STATUS         VARCHAR,
    NUM_VEHICLES_AVAILABLE NUMBER,
    NUM_DOCKS_AVAILABLE    NUMBER,
    SOURCE_FILE            VARCHAR,
    LOAD_ID                VARCHAR,
    CREATED_AT             TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.CORE.FACT_VEHICLE_STATUS
(
    VEHICLE_STATUS_KEY NUMBER AUTOINCREMENT,
    VEHICLE_KEY        NUMBER,
    STATION_KEY        NUMBER,
    DATE_KEY           NUMBER(8,0),
    TIME_KEY           NUMBER(6,0),
    SNAPSHOT_TIMESTAMP TIMESTAMP_NTZ,
    VEHICLE_STATUS     VARCHAR,
    LATITUDE           NUMBER(10,7),
    LONGITUDE          NUMBER(10,7),
    SOURCE_FILE        VARCHAR,
    LOAD_ID            VARCHAR,
    CREATED_AT         TIMESTAMP_NTZ
);

-- ============================================================
-- 05.1 — HISTORICAL STAGING → CORE PROCEDURE
-- ============================================================

CREATE OR REPLACE PROCEDURE DIVVY_DB.CORE.SP_LOAD_HISTORICAL_CORE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO DIVVY_DB.CORE.DIM_DATE
    (
        DATE_KEY, FULL_DATE, DAY_OF_WEEK, DAY_NAME, DAY_OF_MONTH,
        WEEK_OF_YEAR, MONTH_NUMBER, MONTH_NAME, QUARTER_NUMBER,
        YEAR_NUMBER, IS_WEEKEND
    )
    SELECT
        TO_NUMBER(TO_CHAR(D, 'YYYYMMDD')),
        D,
        DAYOFWEEKISO(D),
        DAYNAME(D),
        DAYOFMONTH(D),
        WEEKOFYEAR(D),
        MONTH(D),
        MONTHNAME(D),
        QUARTER(D),
        YEAR(D),
        DAYOFWEEKISO(D) IN (6,7)
    FROM
    (
        SELECT DATEADD('day', SEQ4(), TO_DATE('2020-01-01')) AS D
        FROM TABLE(GENERATOR(ROWCOUNT => 7000))
    )
    WHERE D <= TO_DATE('2039-02-28')
      AND NOT EXISTS
      (
          SELECT 1
          FROM DIVVY_DB.CORE.DIM_DATE X
          WHERE X.FULL_DATE = D
      );

    INSERT INTO DIVVY_DB.CORE.DIM_TIME
    (
        TIME_KEY, FULL_TIME, HOUR_NUMBER, MINUTE_NUMBER,
        SECOND_NUMBER, TIME_BUCKET, PEAK_PERIOD
    )
    SELECT
        TO_NUMBER(TO_CHAR(T, 'HH24MISS')),
        TO_TIME(T),
        HOUR(T),
        MINUTE(T),
        SECOND(T),
        CASE
            WHEN HOUR(T) < 6 THEN 'NIGHT'
            WHEN HOUR(T) < 12 THEN 'MORNING'
            WHEN HOUR(T) < 18 THEN 'AFTERNOON'
            ELSE 'EVENING'
        END,
        CASE
            WHEN HOUR(T) BETWEEN 7 AND 9
              OR HOUR(T) BETWEEN 16 AND 18 THEN 'PEAK'
            ELSE 'OFF_PEAK'
        END
    FROM
    (
        SELECT DATEADD('second', SEQ4(), TO_TIMESTAMP_NTZ('2000-01-01 00:00:00')) AS T
        FROM TABLE(GENERATOR(ROWCOUNT => 86400))
    )
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM DIVVY_DB.CORE.DIM_TIME X
        WHERE X.TIME_KEY = TO_NUMBER(TO_CHAR(T, 'HH24MISS'))
    );

    MERGE INTO DIVVY_DB.CORE.DIM_RIDER T
    USING
    (
        SELECT DISTINCT MEMBER_CASUAL AS RIDER_TYPE
        FROM DIVVY_DB.STAGING.STG_TRIPS
        WHERE MEMBER_CASUAL IS NOT NULL
    ) S
    ON T.RIDER_TYPE = S.RIDER_TYPE
   AND T.SOURCE_SYSTEM = 'DIVVY'
    WHEN MATCHED THEN UPDATE SET IS_CURRENT = TRUE
    WHEN NOT MATCHED THEN INSERT
    (
        RIDER_TYPE, SOURCE_SYSTEM, IS_CURRENT
    )
    VALUES
    (
        S.RIDER_TYPE, 'DIVVY', TRUE
    );

    MERGE INTO DIVVY_DB.CORE.DIM_STATION T
    USING
    (
        SELECT STATION_ID, STATION_NAME, LATITUDE, LONGITUDE
        FROM
        (
            SELECT
                START_STATION_ID AS STATION_ID,
                START_STATION_NAME AS STATION_NAME,
                START_LAT AS LATITUDE,
                START_LNG AS LONGITUDE
            FROM DIVVY_DB.STAGING.STG_TRIPS
            WHERE START_STATION_ID IS NOT NULL

            UNION ALL

            SELECT
                END_STATION_ID,
                END_STATION_NAME,
                END_LAT,
                END_LNG
            FROM DIVVY_DB.STAGING.STG_TRIPS
            WHERE END_STATION_ID IS NOT NULL
        )
        QUALIFY ROW_NUMBER() OVER
        (
            PARTITION BY STATION_ID
            ORDER BY STATION_NAME NULLS LAST
        ) = 1
    ) S
    ON T.STATION_ID = S.STATION_ID
   AND T.SOURCE_SYSTEM = 'DIVVY'
   AND T.IS_CURRENT = TRUE
    WHEN MATCHED THEN UPDATE SET
        STATION_NAME = COALESCE(S.STATION_NAME, T.STATION_NAME),
        LATITUDE = COALESCE(S.LATITUDE, T.LATITUDE),
        LONGITUDE = COALESCE(S.LONGITUDE, T.LONGITUDE)
    WHEN NOT MATCHED THEN INSERT
    (
        STATION_ID, STATION_NAME, LATITUDE, LONGITUDE,
        SOURCE_SYSTEM, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT
    )
    VALUES
    (
        S.STATION_ID, S.STATION_NAME, S.LATITUDE, S.LONGITUDE,
        'DIVVY', CURRENT_TIMESTAMP(), NULL, TRUE
    );

    INSERT INTO DIVVY_DB.CORE.FACT_TRIP
    (
        RIDE_ID, START_DATE_KEY, START_TIME_KEY, END_DATE_KEY, END_TIME_KEY,
        START_STATION_KEY, END_STATION_KEY, RIDER_KEY, RIDEABLE_TYPE,
        STARTED_AT, ENDED_AT, TRIP_DURATION_MINUTES,
        START_LAT, START_LNG, END_LAT, END_LNG,
        SOURCE_FILE, LOAD_ID, CREATED_AT
    )
    SELECT
        S.RIDE_ID,
        TO_NUMBER(TO_CHAR(S.STARTED_AT, 'YYYYMMDD')),
        TO_NUMBER(TO_CHAR(S.STARTED_AT, 'HH24MISS')),
        TO_NUMBER(TO_CHAR(S.ENDED_AT, 'YYYYMMDD')),
        TO_NUMBER(TO_CHAR(S.ENDED_AT, 'HH24MISS')),
        DS.START_STATION_KEY,
        DE.STATION_KEY,
        DR.RIDER_KEY,
        S.RIDEABLE_TYPE,
        S.STARTED_AT,
        S.ENDED_AT,
        S.TRIP_DURATION_MINUTES,
        S.START_LAT,
        S.START_LNG,
        S.END_LAT,
        S.END_LNG,
        S.SOURCE_FILE,
        S.LOAD_ID,
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.STAGING.STG_TRIPS S
    LEFT JOIN DIVVY_DB.CORE.DIM_STATION DS
        ON DS.STATION_ID = S.START_STATION_ID
       AND DS.IS_CURRENT = TRUE
    LEFT JOIN DIVVY_DB.CORE.DIM_STATION DE
        ON DE.STATION_ID = S.END_STATION_ID
       AND DE.IS_CURRENT = TRUE
    LEFT JOIN DIVVY_DB.CORE.DIM_RIDER DR
        ON DR.RIDER_TYPE = S.MEMBER_CASUAL
       AND DR.SOURCE_SYSTEM = 'DIVVY'
    WHERE S.IS_VALID_TIMESTAMP
      AND S.IS_VALID_DURATION
      AND S.IS_VALID_STATION
      AND NOT S.IS_DUPLICATE
      AND NOT EXISTS
      (
          SELECT 1
          FROM DIVVY_DB.CORE.FACT_TRIP F
          WHERE F.RIDE_ID = S.RIDE_ID
            AND COALESCE(F.SOURCE_FILE, '') = COALESCE(S.SOURCE_FILE, '')
      );

    RETURN 'HISTORICAL_CORE_COMPLETE';
END;
$$;

SHOW TABLES IN SCHEMA DIVVY_DB.CORE;
