-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 06 — ANALYTICAL DATA MARTS
-- ============================================================
-- MART tables are curated reporting datasets for Power BI.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_OPERATIONS
(
    DATE_KEY                  NUMBER(8,0),
    TOTAL_TRIPS               NUMBER,
    MEMBER_TRIPS              NUMBER,
    CASUAL_TRIPS              NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    TOTAL_ACTIVE_STATIONS     NUMBER,
    TOTAL_AVAILABLE_VEHICLES  NUMBER,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_STATION
(
    DATE_KEY                  NUMBER(8,0),
    STATION_KEY               NUMBER,
    STATION_ID                VARCHAR,
    STATION_NAME              VARCHAR,
    TRIP_ORIGIN_COUNT         NUMBER,
    TRIP_DESTINATION_COUNT    NUMBER,
    TOTAL_STATION_TRIPS       NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    AVG_VEHICLES_AVAILABLE    NUMBER(12,2),
    AVG_DOCKS_AVAILABLE       NUMBER(12,2),
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_RIDER
(
    DATE_KEY                  NUMBER(8,0),
    RIDER_TYPE                VARCHAR,
    TOTAL_TRIPS               NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    UNIQUE_START_STATIONS     NUMBER,
    UNIQUE_END_STATIONS       NUMBER,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_FLEET
(
    DATE_KEY                NUMBER(8,0),
    VEHICLE_TYPE_ID         VARCHAR,
    VEHICLE_STATUS           VARCHAR,
    VEHICLE_COUNT            NUMBER,
    ACTIVE_VEHICLE_COUNT     NUMBER,
    LAST_SNAPSHOT_TIMESTAMP  TIMESTAMP_NTZ,
    LAST_REFRESHED_AT        TIMESTAMP_NTZ
);

SHOW TABLES IN SCHEMA DIVVY_DB.MART;
