-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 06 — ANALYTICAL DATA MARTS
-- ============================================================
-- MART tables are curated reporting datasets for Power BI.
-- The refresh procedure is reusable by historical loading and
-- the incremental GBFS processing task.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_OPERATIONS
(
    DATE_KEY                  NUMBER(8,0),
    TOTAL_TRIPS               NUMBER,
    MEMBER_TRIPS              NUMBER,
    CASUAL_TRIPS              NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    TOTAL_ACTIVE_STATIONS     NUMBER,
    TOTAL_AVAILABLE_VEHICLES  NUMBER,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_STATION
(
    DATE_KEY                  NUMBER(8,0),
    STATION_KEY               NUMBER,
    STATION_ID                VARCHAR,
    STATION_NAME              VARCHAR,
    TRIP_ORIGIN_COUNT         NUMBER,
    TRIP_DESTINATION_COUNT    NUMBER,
    TOTAL_STATION_TRIPS       NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    AVG_VEHICLES_AVAILABLE    NUMBER(12,2),
    AVG_DOCKS_AVAILABLE       NUMBER(12,2),
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_RIDER
(
    DATE_KEY                  NUMBER(8,0),
    RIDER_TYPE                VARCHAR,
    TOTAL_TRIPS               NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    UNIQUE_START_STATIONS     NUMBER,
    UNIQUE_END_STATIONS       NUMBER,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_FLEET
(
    DATE_KEY                 NUMBER(8,0),
    VEHICLE_TYPE_ID          VARCHAR,
    VEHICLE_STATUS            VARCHAR,
    VEHICLE_COUNT             NUMBER,
    ACTIVE_VEHICLE_COUNT      NUMBER,
    LAST_SNAPSHOT_TIMESTAMP   TIMESTAMP_NTZ,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

-- ============================================================
-- 06.1 — MART REFRESH PROCEDURE
-- ============================================================

CREATE OR REPLACE PROCEDURE DIVVY_DB.MART.SP_REFRESH_MARTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE DIVVY_DB.MART.MART_OPERATIONS;
    TRUNCATE TABLE DIVVY_DB.MART.MART_STATION;
    TRUNCATE TABLE DIVVY_DB.MART.MART_RIDER;
    TRUNCATE TABLE DIVVY_DB.MART.MART_FLEET;

    INSERT INTO DIVVY_DB.MART.MART_OPERATIONS
    SELECT
        F.START_DATE_KEY AS DATE_KEY,
        COUNT(*) AS TOTAL_TRIPS,
        COUNT_IF(R.RIDER_TYPE = 'member') AS MEMBER_TRIPS,
        COUNT_IF(R.RIDER_TYPE = 'casual') AS CASUAL_TRIPS,
        ROUND(AVG(F.TRIP_DURATION_MINUTES), 2),
        COUNT(DISTINCT F.START_STATION_KEY),
        COALESCE(SA.TOTAL_AVAILABLE_VEHICLES, 0),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_TRIP F
    LEFT JOIN DIVVY_DB.CORE.DIM_RIDER R
        ON R.RIDER_KEY = F.RIDER_KEY
    LEFT JOIN
    (
        SELECT DATE_KEY, SUM(NUM_VEHICLES_AVAILABLE) AS TOTAL_AVAILABLE_VEHICLES
        FROM DIVVY_DB.CORE.FACT_STATION_STATUS
        GROUP BY DATE_KEY
    ) SA
        ON SA.DATE_KEY = F.START_DATE_KEY
    GROUP BY F.START_DATE_KEY, SA.TOTAL_AVAILABLE_VEHICLES;

    INSERT INTO DIVVY_DB.MART.MART_STATION
    SELECT
        F.START_DATE_KEY,
        F.START_STATION_KEY,
        S.STATION_ID,
        S.STATION_NAME,
        COUNT(*) AS TRIP_ORIGIN_COUNT,
        COALESCE(D.TRIP_DESTINATION_COUNT, 0),
        COUNT(*) + COALESCE(D.TRIP_DESTINATION_COUNT, 0),
        ROUND(AVG(F.TRIP_DURATION_MINUTES), 2),
        COALESCE(AVG(FS.NUM_VEHICLES_AVAILABLE), 0),
        COALESCE(AVG(FS.NUM_DOCKS_AVAILABLE), 0),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_TRIP F
    LEFT JOIN DIVVY_DB.CORE.DIM_STATION S
        ON S.STATION_KEY = F.START_STATION_KEY
    LEFT JOIN
    (
        SELECT END_DATE_KEY, END_STATION_KEY, COUNT(*) AS TRIP_DESTINATION_COUNT
        FROM DIVVY_DB.CORE.FACT_TRIP
        GROUP BY END_DATE_KEY, END_STATION_KEY
    ) D
        ON D.END_DATE_KEY = F.START_DATE_KEY
       AND D.END_STATION_KEY = F.START_STATION_KEY
    LEFT JOIN DIVVY_DB.CORE.FACT_STATION_STATUS FS
        ON FS.STATION_KEY = F.START_STATION_KEY
       AND FS.DATE_KEY = F.START_DATE_KEY
    GROUP BY
        F.START_DATE_KEY,
        F.START_STATION_KEY,
        S.STATION_ID,
        S.STATION_NAME,
        D.TRIP_DESTINATION_COUNT;

    INSERT INTO DIVVY_DB.MART.MART_RIDER
    SELECT
        F.START_DATE_KEY,
        R.RIDER_TYPE,
        COUNT(*) AS TOTAL_TRIPS,
        ROUND(AVG(F.TRIP_DURATION_MINUTES), 2),
        COUNT(DISTINCT F.START_STATION_KEY),
        COUNT(DISTINCT F.END_STATION_KEY),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_TRIP F
    LEFT JOIN DIVVY_DB.CORE.DIM_RIDER R
        ON R.RIDER_KEY = F.RIDER_KEY
    GROUP BY F.START_DATE_KEY, R.RIDER_TYPE;

    INSERT INTO DIVVY_DB.MART.MART_FLEET
    SELECT
        F.DATE_KEY,
        COALESCE(VT.VEHICLE_TYPE_ID, 'UNKNOWN'),
        F.VEHICLE_STATUS,
        COUNT(*) AS VEHICLE_COUNT,
        COUNT_IF(F.VEHICLE_STATUS NOT IN ('DISABLED', 'INACTIVE')),
        MAX(F.SNAPSHOT_TIMESTAMP),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_VEHICLE_STATUS F
    LEFT JOIN DIVVY_DB.CORE.DIM_VEHICLE V
        ON V.VEHICLE_KEY = F.VEHICLE_KEY
    LEFT JOIN DIVVY_DB.CORE.DIM_VEHICLE_TYPE VT
        ON VT.VEHICLE_TYPE_ID = V.VEHICLE_TYPE_ID
    GROUP BY F.DATE_KEY, COALESCE(VT.VEHICLE_TYPE_ID, 'UNKNOWN'), F.VEHICLE_STATUS;

    RETURN 'MART_REFRESH_COMPLETE';
END;
$$;

SHOW TABLES IN SCHEMA DIVVY_DB.MART;
