-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 06 — ANALYTICAL DATA MARTS
-- ============================================================
-- MART tables are curated reporting datasets for Power BI.
-- The refresh procedure is reusable by historical loading and
-- the incremental GBFS processing task.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_OPERATIONS
(
    DATE_KEY                  NUMBER(8,0),
    TOTAL_TRIPS               NUMBER,
    MEMBER_TRIPS              NUMBER,
    CASUAL_TRIPS              NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    TOTAL_ACTIVE_STATIONS     NUMBER,
    TOTAL_AVAILABLE_VEHICLES  NUMBER,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_STATION
(
    DATE_KEY                  NUMBER(8,0),
    STATION_KEY               NUMBER,
    STATION_ID                VARCHAR,
    STATION_NAME              VARCHAR,
    TRIP_ORIGIN_COUNT         NUMBER,
    TRIP_DESTINATION_COUNT    NUMBER,
    TOTAL_STATION_TRIPS       NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    AVG_VEHICLES_AVAILABLE    NUMBER(12,2),
    AVG_DOCKS_AVAILABLE       NUMBER(12,2),
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_RIDER
(
    DATE_KEY                  NUMBER(8,0),
    RIDER_TYPE                VARCHAR,
    TOTAL_TRIPS               NUMBER,
    AVG_TRIP_DURATION_MINUTES NUMBER(12,2),
    UNIQUE_START_STATIONS     NUMBER,
    UNIQUE_END_STATIONS       NUMBER,
    LAST_REFRESHED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.MART.MART_FLEET
(
    DATE_KEY                NUMBER(8,0),
    VEHICLE_TYPE_ID         VARCHAR,
    VEHICLE_STATUS           VARCHAR,
    VEHICLE_COUNT            NUMBER,
    ACTIVE_VEHICLE_COUNT     NUMBER,
    LAST_SNAPSHOT_TIMESTAMP  TIMESTAMP_NTZ,
    LAST_REFRESHED_AT        TIMESTAMP_NTZ
);

-- ============================================================
-- 06.1 — MART REFRESH PROCEDURE
-- ============================================================

CREATE OR REPLACE PROCEDURE DIVVY_DB.MART.SP_REFRESH_MARTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE DIVVY_DB.MART.MART_OPERATIONS;
    TRUNCATE TABLE DIVVY_DB.MART.MART_STATION;
    TRUNCATE TABLE DIVVY_DB.MART.MART_RIDER;
    TRUNCATE TABLE DIVVY_DB.MART.MART_FLEET;

    -- --------------------------------------------------------
    -- OPERATIONS MART
    -- --------------------------------------------------------

    INSERT INTO DIVVY_DB.MART.MART_OPERATIONS
    (
        DATE_KEY,
        TOTAL_TRIPS,
        MEMBER_TRIPS,
        CASUAL_TRIPS,
        AVG_TRIP_DURATION_MINUTES,
        TOTAL_ACTIVE_STATIONS,
        TOTAL_AVAILABLE_VEHICLES,
        LAST_REFRESHED_AT
    )
    SELECT
        F.START_DATE_KEY,
        COUNT(*) AS TOTAL_TRIPS,
        COUNT_IF(LOWER(R.RIDER_TYPE) = 'member') AS MEMBER_TRIPS,
        COUNT_IF(LOWER(R.RIDER_TYPE) = 'casual') AS CASUAL_TRIPS,
        ROUND(AVG(F.TRIP_DURATION_MINUTES), 2),
        COUNT(DISTINCT F.START_STATION_KEY),
        COALESCE(MAX(SA.TOTAL_AVAILABLE_VEHICLES), 0),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_TRIP F
    LEFT JOIN DIVVY_DB.CORE.DIM_RIDER R
        ON R.RIDER_KEY = F.RIDER_KEY
    LEFT JOIN
    (
        SELECT
            DATE_KEY,
            SUM(NUM_VEHICLES_AVAILABLE) AS TOTAL_AVAILABLE_VEHICLES
        FROM DIVVY_DB.CORE.FACT_STATION_STATUS
        GROUP BY DATE_KEY
    ) SA
        ON SA.DATE_KEY = F.START_DATE_KEY
    GROUP BY F.START_DATE_KEY;

    -- --------------------------------------------------------
    -- STATION MART
    -- --------------------------------------------------------
    -- Station-status snapshots are aggregated before joining to
    -- trip facts so trip counts are not multiplied by snapshots.

    INSERT INTO DIVVY_DB.MART.MART_STATION
    (
        DATE_KEY,
        STATION_KEY,
        STATION_ID,
        STATION_NAME,
        TRIP_ORIGIN_COUNT,
        TRIP_DESTINATION_COUNT,
        TOTAL_STATION_TRIPS,
        AVG_TRIP_DURATION_MINUTES,
        AVG_VEHICLES_AVAILABLE,
        AVG_DOCKS_AVAILABLE,
        LAST_REFRESHED_AT
    )
    SELECT
        O.DATE_KEY,
        O.STATION_KEY,
        S.STATION_ID,
        S.STATION_NAME,
        O.TRIP_ORIGIN_COUNT,
        COALESCE(D.TRIP_DESTINATION_COUNT, 0),
        O.TRIP_ORIGIN_COUNT + COALESCE(D.TRIP_DESTINATION_COUNT, 0),
        O.AVG_TRIP_DURATION_MINUTES,
        COALESCE(FS.AVG_VEHICLES_AVAILABLE, 0),
        COALESCE(FS.AVG_DOCKS_AVAILABLE, 0),
        CURRENT_TIMESTAMP()
    FROM
    (
        SELECT
            START_DATE_KEY AS DATE_KEY,
            START_STATION_KEY AS STATION_KEY,
            COUNT(*) AS TRIP_ORIGIN_COUNT,
            ROUND(AVG(TRIP_DURATION_MINUTES), 2) AS AVG_TRIP_DURATION_MINUTES
        FROM DIVVY_DB.CORE.FACT_TRIP
        GROUP BY START_DATE_KEY, START_STATION_KEY
    ) O
    LEFT JOIN DIVVY_DB.CORE.DIM_STATION S
        ON S.STATION_KEY = O.STATION_KEY
    LEFT JOIN
    (
        SELECT
            END_DATE_KEY AS DATE_KEY,
            END_STATION_KEY AS STATION_KEY,
            COUNT(*) AS TRIP_DESTINATION_COUNT
        FROM DIVVY_DB.CORE.FACT_TRIP
        GROUP BY END_DATE_KEY, END_STATION_KEY
    ) D
        ON D.DATE_KEY = O.DATE_KEY
       AND D.STATION_KEY = O.STATION_KEY
    LEFT JOIN
    (
        SELECT
            STATION_KEY,
            DATE_KEY,
            ROUND(AVG(NUM_VEHICLES_AVAILABLE), 2) AS AVG_VEHICLES_AVAILABLE,
            ROUND(AVG(NUM_DOCKS_AVAILABLE), 2) AS AVG_DOCKS_AVAILABLE
        FROM DIVVY_DB.CORE.FACT_STATION_STATUS
        GROUP BY STATION_KEY, DATE_KEY
    ) FS
        ON FS.STATION_KEY = O.STATION_KEY
       AND FS.DATE_KEY = O.DATE_KEY;

    -- --------------------------------------------------------
    -- RIDER MART
    -- --------------------------------------------------------

    INSERT INTO DIVVY_DB.MART.MART_RIDER
    (
        DATE_KEY,
        RIDER_TYPE,
        TOTAL_TRIPS,
        AVG_TRIP_DURATION_MINUTES,
        UNIQUE_START_STATIONS,
        UNIQUE_END_STATIONS,
        LAST_REFRESHED_AT
    )
    SELECT
        F.START_DATE_KEY,
        R.RIDER_TYPE,
        COUNT(*) AS TOTAL_TRIPS,
        ROUND(AVG(F.TRIP_DURATION_MINUTES), 2),
        COUNT(DISTINCT F.START_STATION_KEY),
        COUNT(DISTINCT F.END_STATION_KEY),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_TRIP F
    LEFT JOIN DIVVY_DB.CORE.DIM_RIDER R
        ON R.RIDER_KEY = F.RIDER_KEY
    GROUP BY F.START_DATE_KEY, R.RIDER_TYPE;

    -- --------------------------------------------------------
    -- FLEET MART
    -- --------------------------------------------------------

    INSERT INTO DIVVY_DB.MART.MART_FLEET
    (
        DATE_KEY,
        VEHICLE_TYPE_ID,
        VEHICLE_STATUS,
        VEHICLE_COUNT,
        ACTIVE_VEHICLE_COUNT,
        LAST_SNAPSHOT_TIMESTAMP,
        LAST_REFRESHED_AT
    )
    SELECT
        F.DATE_KEY,
        COALESCE(VT.VEHICLE_TYPE_ID, 'UNKNOWN'),
        F.VEHICLE_STATUS,
        COUNT(*) AS VEHICLE_COUNT,
        COUNT_IF(UPPER(COALESCE(F.VEHICLE_STATUS, 'UNKNOWN')) NOT IN ('DISABLED', 'INACTIVE')),
        MAX(F.SNAPSHOT_TIMESTAMP),
        CURRENT_TIMESTAMP()
    FROM DIVVY_DB.CORE.FACT_VEHICLE_STATUS F
    LEFT JOIN DIVVY_DB.CORE.DIM_VEHICLE V
        ON V.VEHICLE_KEY = F.VEHICLE_KEY
    LEFT JOIN DIVVY_DB.CORE.DIM_VEHICLE_TYPE VT
        ON VT.VEHICLE_TYPE_ID = V.VEHICLE_TYPE_ID
       AND VT.IS_CURRENT = TRUE
    GROUP BY
        F.DATE_KEY,
        COALESCE(VT.VEHICLE_TYPE_ID, 'UNKNOWN'),
        F.VEHICLE_STATUS;

    RETURN 'MART_REFRESH_COMPLETE';
END;
$$;

SHOW TABLES IN SCHEMA DIVVY_DB.MART;
