-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 11 — QUALITY, AUDIT & VALIDATION
-- ============================================================
-- Purpose:
--   Centralize operational audit metadata and repeatable checks
--   across RAW, STAGING, CORE and MART.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE TABLE IF NOT EXISTS DIVVY_DB.AUDIT.PIPELINE_RUN
(
    PIPELINE_RUN_ID    VARCHAR,
    PIPELINE_NAME      VARCHAR,
    SOURCE_SYSTEM      VARCHAR,
    SOURCE_FILE        VARCHAR,
    START_TIME         TIMESTAMP_NTZ,
    END_TIME           TIMESTAMP_NTZ,
    STATUS             VARCHAR,
    RECORDS_PROCESSED  NUMBER,
    RECORDS_REJECTED   NUMBER,
    ERROR_MESSAGE      VARCHAR
);

CREATE TABLE IF NOT EXISTS DIVVY_DB.AUDIT.DATA_QUALITY_RESULT
(
    CHECK_ID        VARCHAR,
    CHECK_NAME      VARCHAR,
    LAYER           VARCHAR,
    OBJECT_NAME     VARCHAR,
    CHECK_TIME      TIMESTAMP_NTZ,
    STATUS          VARCHAR,
    RECORDS_CHECKED NUMBER,
    RECORDS_FAILED  NUMBER,
    DETAILS         VARCHAR
);

CREATE OR REPLACE VIEW DIVVY_DB.AUDIT.VW_PIPELINE_FAILURES AS
SELECT *
FROM DIVVY_DB.AUDIT.PIPELINE_RUN
WHERE STATUS IN ('FAILED', 'ERROR');

CREATE OR REPLACE VIEW DIVVY_DB.AUDIT.VW_RECENT_PIPELINE_RUNS AS
SELECT *
FROM DIVVY_DB.AUDIT.PIPELINE_RUN
ORDER BY START_TIME DESC;

-- ============================================================
-- RAW VALIDATION
-- ============================================================

SELECT COUNT(*) AS RAW_TRIPS_COUNT
FROM DIVVY_DB.RAW.RAW_TRIPS;

SELECT
    MEMBER_CASUAL,
    COUNT(*) AS TRIP_COUNT
FROM DIVVY_DB.RAW.RAW_TRIPS
GROUP BY MEMBER_CASUAL
ORDER BY TRIP_COUNT DESC;

SELECT COUNT(*) AS DUPLICATE_RIDE_IDS
FROM
(
    SELECT RIDE_ID
    FROM DIVVY_DB.RAW.RAW_TRIPS
    GROUP BY RIDE_ID
    HAVING COUNT(*) > 1
);

SELECT COUNT(*) AS INVALID_TIMESTAMPS
FROM DIVVY_DB.RAW.RAW_TRIPS
WHERE STARTED_AT IS NULL
   OR ENDED_AT IS NULL
   OR ENDED_AT < STARTED_AT;

SELECT COUNT(*) AS INVALID_COORDINATES
FROM DIVVY_DB.RAW.RAW_TRIPS
WHERE (START_LAT IS NOT NULL AND (START_LAT < -90 OR START_LAT > 90))
   OR (START_LNG IS NOT NULL AND (START_LNG < -180 OR START_LNG > 180))
   OR (END_LAT IS NOT NULL AND (END_LAT < -90 OR END_LAT > 90))
   OR (END_LNG IS NOT NULL AND (END_LNG < -180 OR END_LNG > 180));

-- ============================================================
-- OBJECT VALIDATION
-- ============================================================

SHOW TABLES IN SCHEMA DIVVY_DB.RAW;
SHOW TABLES IN SCHEMA DIVVY_DB.STAGING;
SHOW TABLES IN SCHEMA DIVVY_DB.CORE;
SHOW TABLES IN SCHEMA DIVVY_DB.MART;

SELECT COUNT(*) AS STG_TRIPS_COUNT
FROM DIVVY_DB.STAGING.STG_TRIPS;

SELECT COUNT(*) AS FACT_TRIP_COUNT
FROM DIVVY_DB.CORE.FACT_TRIP;

SELECT COUNT(*) AS MART_OPERATIONS_COUNT
FROM DIVVY_DB.MART.MART_OPERATIONS;

SELECT COUNT(*) AS MART_STATION_COUNT
FROM DIVVY_DB.MART.MART_STATION;

SELECT COUNT(*) AS MART_RIDER_COUNT
FROM DIVVY_DB.MART.MART_RIDER;

SELECT COUNT(*) AS MART_FLEET_COUNT
FROM DIVVY_DB.MART.MART_FLEET;

SELECT *
FROM DIVVY_DB.AUDIT.VW_RECENT_PIPELINE_RUNS
LIMIT 20;
