-- ============================================================
-- URBAN MOBILITY & FLEET INTELLIGENCE
-- 14 — POWER BI REPORTING VIEWS
-- ============================================================
-- Purpose:
--   Provide Power BI-friendly views over curated MART tables.
--   Power BI should consume these views or the MART tables only.
-- ============================================================

USE DATABASE DIVVY_DB;

CREATE OR REPLACE VIEW DIVVY_DB.MART.VW_POWERBI_OPERATIONS AS
SELECT
    DATE_KEY,
    TO_DATE(TO_VARCHAR(DATE_KEY), 'YYYYMMDD') AS REPORT_DATE,
    TOTAL_TRIPS,
    MEMBER_TRIPS,
    CASUAL_TRIPS,
    AVG_TRIP_DURATION_MINUTES,
    TOTAL_ACTIVE_STATIONS,
    TOTAL_AVAILABLE_VEHICLES,
    LAST_REFRESHED_AT
FROM DIVVY_DB.MART.MART_OPERATIONS;

CREATE OR REPLACE VIEW DIVVY_DB.MART.VW_POWERBI_STATION AS
SELECT
    DATE_KEY,
    TO_DATE(TO_VARCHAR(DATE_KEY), 'YYYYMMDD') AS REPORT_DATE,
    STATION_KEY,
    STATION_ID,
    STATION_NAME,
    TRIP_ORIGIN_COUNT,
    TRIP_DESTINATION_COUNT,
    TOTAL_STATION_TRIPS,
    AVG_TRIP_DURATION_MINUTES,
    AVG_VEHICLES_AVAILABLE,
    AVG_DOCKS_AVAILABLE,
    LAST_REFRESHED_AT
FROM DIVVY_DB.MART.MART_STATION;

CREATE OR REPLACE VIEW DIVVY_DB.MART.VW_POWERBI_RIDER AS
SELECT
    DATE_KEY,
    TO_DATE(TO_VARCHAR(DATE_KEY), 'YYYYMMDD') AS REPORT_DATE,
    RIDER_TYPE,
    TOTAL_TRIPS,
    AVG_TRIP_DURATION_MINUTES,
    UNIQUE_START_STATIONS,
    UNIQUE_END_STATIONS,
    LAST_REFRESHED_AT
FROM DIVVY_DB.MART.MART_RIDER;

CREATE OR REPLACE VIEW DIVVY_DB.MART.VW_POWERBI_FLEET AS
SELECT
    DATE_KEY,
    TO_DATE(TO_VARCHAR(DATE_KEY), 'YYYYMMDD') AS REPORT_DATE,
    VEHICLE_TYPE_ID,
    VEHICLE_STATUS,
    VEHICLE_COUNT,
    ACTIVE_VEHICLE_COUNT,
    LAST_SNAPSHOT_TIMESTAMP,
    LAST_REFRESHED_AT
FROM DIVVY_DB.MART.MART_FLEET;

SHOW VIEWS IN SCHEMA DIVVY_DB.MART;
