USE DATABASE DIVVY_DB;

DROP TABLE IF EXISTS DIVVY_DB.CORE.FACT_VEHICLE_STATUS;
DROP TABLE IF EXISTS DIVVY_DB.CORE.FACT_STATION_STATUS;
DROP TABLE IF EXISTS DIVVY_DB.CORE.FACT_TRIP;

DROP TABLE IF EXISTS DIVVY_DB.CORE.DIM_VEHICLE;
DROP TABLE IF EXISTS DIVVY_DB.CORE.DIM_VEHICLE_TYPE;
DROP TABLE IF EXISTS DIVVY_DB.CORE.DIM_STATION;
DROP TABLE IF EXISTS DIVVY_DB.CORE.DIM_RIDER;
DROP TABLE IF EXISTS DIVVY_DB.CORE.DIM_TIME;
DROP TABLE IF EXISTS DIVVY_DB.CORE.DIM_DATE;

DROP TABLE IF EXISTS DIVVY_DB.MART.MART_OPERATIONS;
DROP TABLE IF EXISTS DIVVY_DB.MART.MART_STATION;
DROP TABLE IF EXISTS DIVVY_DB.MART.MART_RIDER;
DROP TABLE IF EXISTS DIVVY_DB.MART.MART_FLEET;